### ISSUE TITLE
Apollo1 has a 404 nginx error on apollo2-dev

### ISSUE THREAD

**Issue by mpoelchau** [NAL-i5K/general_issues#122]
Apollo1 test URL: https://apollo2-dev.nal.usda.gov/bacole/jbrowse

We tried the following (@g8tor hopefully remembers more):
- change existing nginx config
- copy old config over and modify it

Note that it looks like it takes nginx a couple of hours to register the config changes - perhaps there are tmp files somewhere that need to be deleted for more effective testing?

**Comment by g8tor** [comment]
Fixed this issue: Write  a quick scrit to check response codes on all deployed wars in /usr/local/apollo/webapps/. The reults are below. @childers or @mpoelchau Please confirm and close this issue since all apollo1 apps returned a 200 (Success) code.

Check https://apollo2-dev.nal.usda.gov/agrpla/jbrowse/ => Status: 200
Check https://apollo2-dev.nal.usda.gov/bacole/jbrowse/ => Status: 200
Check https://apollo2-dev.nal.usda.gov/diacit_legacy/jbrowse/ => Status: 200
Check https://apollo2-dev.nal.usda.gov/diavir/jbrowse/ => Status: 200
Check https://apollo2-dev.nal.usda.gov/euraff/jbrowse/ => Status: 200
Check https://apollo2-dev.nal.usda.gov/helvir/jbrowse/ => Status: 200
Check https://apollo2-dev.nal.usda.gov/homvit/jbrowse/ => Status: 200
Check https://apollo2-dev.nal.usda.gov/ladful/jbrowse/ => Status: 200
Check https://apollo2-dev.nal.usda.gov/odobru_training/jbrowse/ => Status: 200
Check https://apollo2-dev.nal.usda.gov/onttau/jbrowse/ => Status: 200
Check https://apollo2-dev.nal.usda.gov/partep/jbrowse/ => Status: 200

**Comment by mpoelchau** [comment]
Looks like the jbrowse URLs resolve, awesome!

However, you still can't log in. You can see this by either going to the login page (e.g. https://apollo2-dev.nal.usda.gov/onttau/sequences - gives a 404) or clicking on the login button on the top right of the jbrowse page (e.g. from https://apollo2-dev.nal.usda.gov/onttau/jbrowse/)

**Comment by g8tor** [comment]
@mpoelchau  There were a few issues here. The biggest of which was the misconfigured proxy for apollo1 applications. Once I fixed the apollo1 proxy configs, the websockets connected, the apollo1 application are now working correctly and all of them work correctly under http and https.

One other issue was the "upgrade" that need to happen in the case of websockets. The fix was to add the following to the /apollo location in the /etc/nginx/conf.d/apollo.conf file:

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;

Closing this issue
